### ISSUE TITLE
if connection isn't successful application closes.

### ISSUE THREAD

**Issue by immeraufdemhund** [lyc8503/MinecraftRCONClient#1]
Looks like you might have either an uncaught exception or don't gracefully handle the connection problem

**Comment by creeper6530** [comment]
> Looks like you might have either an uncaught exception or don't gracefully handle the connection problem

Tried with lastest version and doesn't imittadely quit, it shows popup warning and after closing the popup, program quits. Was it the issue you meaned?

P. S.: Sorry for my bad English

**Comment by lyc8503** [comment]
> > Looks like you might have either an uncaught exception or don't gracefully handle the connection problem
> 
> Tried with lastest version and doesn't imittadely quit, it shows popup warning and after closing the popup, program quits. Was it the issue you meaned?
> 
> P. S.: Sorry for my bad English

Yes, it shows a warning before exiting.
This is really not a user-friendly design. (It's one of my early works written long ago.)
Fixed it now.
