### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by creeper6530** [lyc8503/MinecraftRCONClient#2]
Tip: Can you add mailto link on the "About" tab? It'll be better. I even can't copy the email.

Just for explanation, mailto link is link in this format:
`mailto:youremail@yourprovider.suffix`
Example:
`mailto:test@gmail.com`

P.S.: Sorry for potential mistakes, I'm not good in English.

**Comment by lyc8503** [comment]
Thanks! Already changed that in the code.
